issues = [
    {"id": 1, "simple_id": 34, "description": "Board.js - board = tmp; direct state mutation"},
    {"id": 2, "simple_id": 114, "description": "Timer.js - time inconsistent state update"},
    {"id": 3, "simple_id": 130, "description": "Timer.js - there is a newline after return, which causes the object literal to be interpreted as a block"},
    {"id": 4, "simple_id": 0, "description": "Navbar.js - the Toggle class should be a separate file"},
    {"id": 5, "simple_id": 0, "description": "Navbar.js - the Toggle class component should be a state component instead, in order to be consistent with the rest of the project"},
    {"id": 6, "simple_id": 149, "description": "Navbar.js - handleClock in Toggle component is unbound"},
    {"id": 7, "simple_id": 181, "description": "sudokuGenerator.js - use of returnless function removeDigits"},
    {"id": 8, "simple_id": 184, "description": "sudokuGenerator.js - useless assignement to a local variable removedDigits"},
    {"id": 9, "simple_id": 178, "description": "Navbar.js - Toggle class extends React.Component, but is missing the super() constructor"},
    {"id": 10, "simple_id": 208, "description": "404.js doesn't use strict comparison"},
    {"id": 11, "simple_id": 48, "description": "_variables.scss - duplicate variable $primary"},
    {"id": 12, "simple_id": 0, "description": "Landing.js - <Main> tag can be collapsed"},
    {"id": 13, "simple_id": 0, "description": "checker.js - count === 1 should be count > 1 to ensure there are no duplicate occurences of a number in a column"},
]

files_included = [
    'tests/js/big_repo/original/sudoku_game/algorithms/checker.js',
    'tests/js/big_repo/original/sudoku_game/algorithms/sudokuGenerator.js',
    'tests/js/big_repo/original/sudoku_game/algorithms/sudokuSolver.js',
    'tests/js/big_repo/original/sudoku_game/animations/pieces.js',
    'tests/js/big_repo/original/sudoku_game/components/board/Board.js',
    'tests/js/big_repo/original/sudoku_game/components/board/Numpad.js',
    'tests/js/big_repo/original/sudoku_game/components/board/Timer.js',
    'tests/js/big_repo/original/sudoku_game/components/buttons/Check.js',
    'tests/js/big_repo/original/sudoku_game/components/buttons/Clear.js',
    'tests/js/big_repo/original/sudoku_game/components/buttons/Regen.js',
    'tests/js/big_repo/original/sudoku_game/components/buttons/Solve.js',
    'tests/js/big_repo/original/sudoku_game/hooks/Sudoku.js',
    'tests/js/big_repo/original/sudoku_game/hooks/Timer.js',
    'tests/js/big_repo/original/sudoku_game/layout/Main.js',
    'tests/js/big_repo/original/sudoku_game/layout/Navbar.js',
    'tests/js/big_repo/original/sudoku_game/layout/Navigation.js',
    'tests/js/big_repo/original/sudoku_game/pages/404.js',
    'tests/js/big_repo/original/sudoku_game/pages/Landing.js',
    'tests/js/big_repo/original/sudoku_game/sass/_resets.scss',
    'tests/js/big_repo/original/sudoku_game/sass/_variables.scss',
    'tests/js/big_repo/original/sudoku_game/sass/main.scss',
    'tests/js/big_repo/original/sudoku_game/App.js',
    'tests/js/big_repo/original/sudoku_game/index.js'
]